### ISSUE TITLE
Not catched Excpetions in AbstractVIewHelper

### ISSUE THREAD

**Issue by monofone** [networkteam/Networkteam.SentryClient#2]
In Production context an exception thrown by a view helper does not bubble to the error handler as the exception is catched and only logged.

See AbstractViewHelper ~265

An idea is to create an aspect around the render method and in case this one throws an exception this will be catched and forwarded to the sentry client.

**Comment by dompie** [comment]
Sentry client can handle exceptions from viewHelpers from change 6e558f85950fd129ffe87ba67c6b0f613f4ada85
