### ISSUE TITLE
Flow-only package needed since Flow 5.x?

### ISSUE THREAD

**Issue by DavidSporer** [networkteam/Networkteam.SentryClient#23]
Hi,

since the excludeClasses setting has been removed with Flow 5 I think we need a Flow only version of this package and - ideally - let this package depend on it.
Otherwhise there's a class depending on another class that's not there (the AOP stuff for Neos).
I've forked this package and removed everything Neos (https://github.com/DavidSporer/Networkteam.SentryClient/tree/flow-only). Maybe that's an option. I'm already using it for a couple of weeks now in our projects.

Cheers,
David

**Comment by kaystrobach** [comment]
https://github.com/neos/flow-development-collection/pull/1252/files

**Comment by kaystrobach** [comment]
solved in master imho, as the fusion handler is now gone - still there is no 5.x release

**Comment by DavidSporer** [comment]
@kaystrobach yes, you're right. Works with Flow 5.x in the meantime.

**Comment by hlubek** [comment]
There's a 5.0 (and 5.1) release that works with Flow 5.x
